/* Generated by powerful Codeforces Tool
 * Author: Tiwent
 * Time: 2020-12-30 22:35:38
 **/

#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <iostream>
#include <map>
#include <queue>
#include <random>
#include <set>
#include <stack>
#include <string>
#include <unordered_map>
#include <vector>

using namespace std;

typedef long long ll;

// const int mod = 998244353;
const int mod = 1e9 + 7;
const int maxn = 5e5 + 5;

int cnt = 0;
vector<int> ans;
bool vis[maxn];

ll qp(ll a, ll b) {
    ll ans = 1;
    while (b) {
        if (b & 1) {
            ans = ans * a % mod;
        }
        b >>= 1;
        a = a * a % mod;
    }
    return ans;
}

int fa[maxn];

int find(int x) {
    return x == fa[x] ? x : fa[x] = find(fa[x]);
}


int main() {
    int n, m;
    scanf("%d%d", &n, &m);
    for (int i = 1; i <= m; i++) fa[i] = i;

    for (int i = 1; i <= n; i++) {
        int k;
        scanf("%d", &k);
        if (k == 1) {
            int a;
            scanf("%d", &a);
            a = find(a);
            if (!vis[a]) {
                vis[a] = 1;
                cnt++;
                ans.push_back(i);
            }
        } else {
            int a, b;
            scanf("%d %d", &a, &b);
            a = find(a);
            b = find(b);
            if (a == b) continue;
            if (a > b) swap(a, b);
            if (!vis[a] || !vis[b]) {
                vis[a] |= vis[b];
                fa[b] = a;
                cnt++;
                ans.push_back(i);
            }
        }
    }


    printf("%lld %d\n", qp(2, cnt), cnt);
    for (auto i : ans) {
        printf("%d ", i);
    }
    printf("\n");


    return 0;
}