/* Generated by powerful Codeforces Tool
 * Author: Tiwent
 * Time: 2020-12-30 22:35:38
 **/

#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <iostream>
#include <map>
#include <queue>
#include <random>
#include <set>
#include <stack>
#include <string>
#include <unordered_map>
#include <vector>

using namespace std;

typedef long long ll;

// const int mod = 998244353;
const int mod = 1e9 + 7;
const int maxn = 1e5 + 5;

ll a[maxn];

int in[maxn];

int main() {
    int T;
    cin >> T;
    while (T--) {
        int n;
        cin >> n;
        for (int i = 1; i <= n; i++) {
            in[i] = 0;
        }
        ll ans = 0;
        for (int i = 1; i <= n; i++) {
            cin >> a[i];
            ans += a[i];
        }
        for (int i = 1; i < n; i++) {
            int x, y;
            cin >> x >> y;
            in[x]++;
            in[y]++;
        }

        priority_queue<pair<int, int>> q;

        for (int i = 1; i <= n; i++) {
            in[i]--;
            if (in[i] > 0) {
                q.push({a[i], in[i]});
            }

        }
        cout << ans << " ";

        while (!q.empty()) {
            pair<int, int> now = q.top();
            q.pop();
            now.second--;
            ans += now.first;
            if (now.second > 0) q.push(now);
            cout << ans << " ";
        }
        cout << endl;
    }


    return 0;
}