/* Generated by powerful Codeforces Tool
 * Author: Tiwent
 * Time: 2020-12-30 22:35:38
 **/

#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <iostream>
#include <map>
#include <queue>
#include <random>
#include <set>
#include <stack>
#include <string>
#include <unordered_map>
#include <vector>

using namespace std;

typedef long long ll;

// const int mod = 998244353;
const int mod = 1e9 + 7;
const int maxn = 1e5 + 5;

int main() {
    int T;
    cin >> T;
    while (T--) {
        string s;
        cin >> s;
        int n = s.length();
        int vis[30];
        memset(vis, 0, sizeof(vis));
        int ans = 0;
        for (int i = 1; i < n; i++) {
            if (s[i] == s[i - 1] || (i >= 2 && s[i] == s[i - 2])) {
                vis[s[i - 1] - 'a'] = 1;
                if (i >= 2) {
                    vis[s[i - 2] - 'a'] = 1;
                }
                if (i + 1 < n) {
                    vis[s[i + 1] - 'a'] = 1;
                }
                if (i + 2 < n) {
                    vis[s[i + 2] - 'a'] = 1;
                }
                for (int j = 0; j < 26; j++) {
                    if (!vis[j]) {
                        s[i] = 'a' + j;
                        break;
                    }
                }
                vis[s[i - 1] - 'a'] = 0;
                if (i >= 2) {
                    vis[s[i - 2] - 'a'] = 0;
                }
                if (i + 1 < n) {
                    vis[s[i + 1] - 'a'] = 0;
                }
                if (i + 2 < n) {
                    vis[s[i + 2] - 'a'] = 0;
                }
                ans++;
            }
        }
        cout << ans << endl;
    }


    return 0;
}