/* Generated by powerful Codeforces Tool
 * Author: Tiwent
 * Time: 2020-12-27 00:00:04
**/

#pragma clang diagnostic ignored "-Wdeprecated-declarations"
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <iostream>
#include <map>
#include <queue>
#include <random>
#include <set>
#include <stack>
#include <string>
#include <unordered_map>
#include <vector>
using namespace std;

typedef long long ll;

//const int mod = 998244353;
const int mod = 1e9 + 7;
const int maxn = 1e5 + 5;

int main()
{
    int n;
    cin >> n;
    cout << n << endl;

    return 0;
}