/* Generated by powerful Codeforces Tool
 * Author: Tiwent
 * Time: 2020-12-30 20:48:18
 **/

#include <bits/stdc++.h>

using namespace std;

typedef long long ll;

// const int mod = 998244353;
const int mod = 1e9 + 7;
const int maxn = 1e5 + 5;

int main() {
    int T;
    cin >> T;
    while (T--) {
        int n;
        cin >> n;
        vector<int> v(n);
        for (int i = 0; i < n; i++) {
            cin >> v[i];
        }
        set<int> s;
        for (int i = 0; i < n; i++) {
            for (int j = i + 1; j < n; j++) {
                s.insert(v[j] - v[i]);
            }
        }
        cout << s.size() << endl;
    }

    return 0;
}
