/* Generated by powerful Codeforces Tool
 * Author: Tiwent
 * Time: 2020-12-30 22:35:02
 **/

#include <bits/stdc++.h>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <iostream>
#include <map>
#include <queue>
#include <random>
#include <set>
#include <stack>
#include <string>
#include <unordered_map>
#include <vector>

using namespace std;

typedef long long ll;

// const int mod = 998244353;
const int mod = 1e9 + 7;
const int maxn = 1e5 + 5;

int v[55];

int main() {
    int T;
    cin >> T;
    while (T--) {
        int n;
        cin >> n;
        for (int i = 0; i < n; i++) {
            cin >> v[i];
        }
        map<int, int> w;
        for (int i = 0; i < n; i++) {
            for (int j = i + 1; j < n; j++) {
                w[v[j] - v[i]] = 1;
            }
        }
        cout << w.size() << endl;
    }

    return 0;
}
