/* Generated by powerful Codeforces Tool
 * Author: Tiwent
 * Time: 2020-12-30 22:35:38
 **/

#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <iostream>
#include <map>
#include <queue>
#include <random>
#include <set>
#include <stack>
#include <string>
#include <unordered_map>
#include <vector>

using namespace std;

typedef long long ll;

// const int mod = 998244353;
const int mod = 1e9 + 7;
const int maxn = 1e5 + 5;

int main() {
    int T;
    cin >> T;
    while (T--) {
        int n;
        cin >> n;
        vector<int> v(n);
        for (int i = 0; i < n; i++) cin >> v[i];
        sort(v.begin(), v.end());

        int ans = 0;
        for (int i = n - 1; i >= 0; i--) {
            if (i == n - 1) v[i]++, ans++;
            else {
                if (v[i] + 1 < v[i + 1]) {
                    ans++;
                    v[i]++;
                } else if (v[i] + 1 == v[i + 1]) {
                    ans++;
                }
            }
        }
        cout << ans << endl;
    }


    return 0;
}